# Generated by Django 4.2.8 on 2024-01-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
